exclude: ".git"

repos:
  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 1.4.0.dev1
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        pass_filenames: false
        args: ["search-path", "backend"]
        additional_dependencies:
          # any dependencies required for the backend development
          # must be defined here to avoid missing-arguments during type checking
          - fastapi==0.103.1
          - pydantic-settings==2.0.3
          - httpx==0.25.0
          - faker
          - pytest

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-c", "backend/pyproject.toml"]
        additional_dependencies: [".[toml]"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: ["."]
