[tool.black]
line-length = 80
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-ra",
    "-q",
    "--cov",
    "--cov-fail-under=100",
    "--no-cov-on-fail",
]
testpaths = [
    "tests"
]

[tool.coverage.run]
omit = [
    "tests/*",
]

[tool.coverage.report]
skip_empty = true
