[tool.bandit]
exclude_dirs = ["tests"]

[tool.coverage.report]
skip_empty = true

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "==0.103.1"
pydantic-settings = "==2.0.3"
uvicorn = { version = "==0.23.2", extras = ["standard"] }
httpx = "==0.25.0"
faker = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-sugar = "*"
ipdb = "*"
pyrefly = "*"
bandit = "*"
ruff = "*"
detect-secrets = "*"
toml-sort = "*"
yamllint = "*"

[tool.pyrefly]
project_includes = [
  "**/*.py"
]
search_path = [
  "."
]
python_version = "3.10"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
  "-ra",
  "-q",
  "--cov",
  "--cov-report=xml",
  "--cov-fail-under=100",
  "--no-cov-on-fail"
]
testpaths = [
  "tests"
]

[tool.ruff]
exclude = [
  ".git",
  "__pycache__",
  ".tox",
  ".venv",
  "node_modules"
]
line-length = 80
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = [
  "E",
  "F",
  "W",
  "I",
  "N",
  "COM",
  "T20",
  "RET",
  "DTZ",
  "PL"
]
ignore = []

[tool.tomlsort]
all = true
in_place = true
no_comments = true
no_header_comments = true
no_footer_comments = true
no_inline_comments = true
no_block_comments = true
no_sort_tables = true
sort_inline_tables = true
sort_inline_arrays = true
spaces_before_inline_comment = 2
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
check = true
ignore_case = true
