[tool.bandit]
exclude_dirs = ["tests"]

[tool.coverage.report]
skip_empty = true

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
fastapi = "==0.141.1"
pydantic-settings = "==2.15.0"
uvicorn = { version = "==0.53.0", extras = ["standard"] }
httpx = "==0.28.1"
faker = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-sugar = "*"
ipdb = "*"
pyrefly = "*"
bandit = "*"
ruff = "*"
detect-secrets = "*"
yamllint = "*"

[tool.pyrefly]
project_includes = [
  "**/*.py"
]
search_path = [
  "."
]
python_version = "3.14"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
  "-ra",
  "-q",
  "--no-cov-on-fail",
]
markers = [
  "unit: isolated tests for a single component",
  "functional: tests that exercise the application through its public interface"
]
testpaths = [
  "tests"
]

[tool.ruff]
exclude = [
  ".git",
  "__pycache__",
  ".tox",
  ".venv",
  "node_modules"
]
line-length = 80
target-version = "py314"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = [
  "E",
  "F",
  "W",
  "I",
  "N",
  "COM",
  "T20",
  "RET",
  "DTZ",
  "PL"
]
ignore = []
