version: "3.8"

services:

  frontend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-frontend
    command: npm run dev
    container_name: frontend
    ports:
      - 8999:8999
    volumes:
      - type: bind
        source: ../frontend
        target: /srv/app
      - /srv/app/node_modules
    working_dir: /srv/app

  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-backend
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ../backend
        target: /app
    working_dir: /app
