# get image
FROM python:3.10-slim

# set working directory
WORKDIR /app

# copy files to working directory
COPY ./backend /app

# install dependencies
RUN pip install -r /app/requirements-dev.txt

# run web app server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000",  "--reload"]
